### ISSUE TITLE
The 'get' command line option should also output in 'directory' format

### ISSUE THREAD

**Issue by diranged** [Nextdoor/ndserviceregistry#28]
The current 'get' CLI tool outputs in JSON or YAML. It should also output in a pure 'directory list' format. For example:

```
Matts-MacBook-Pro:ndserviceregistry-diranged diranged$ python nd_service_registry/bin/ndsr/ndsr.py --server '33.33.33.100:2181' --loglevel 50 --recursive --outputformat yaml
/:
  children:
  - //tests:
      children:
      - //tests/locks-c431b5f97ff84088a083acff5e5cc591-__lock__:
          children: []
      - //tests/locks-954726f9903d4d60b30e1e6508c693e7-__lock__:
          children: []
      - //tests/locks-9f1ca6f67c67499e9dcf7ffeaa82f0a3-__lock__:
          children: []
```

In directory format, it would look like this:

```
Matts-MacBook-Pro:ndserviceregistry-diranged diranged$ python nd_service_registry/bin/ndsr/ndsr.py --server '33.33.33.100:2181' --loglevel 50 --recursive --outputformat dir
/
/tests
/tests/locks-c431b5f97ff84088a083acff5e5cc591-__lock__
/tests/locks-954726f9903d4d60b30e1e6508c693e7-__lock__
/tests/locks-9f1ca6f67c67499e9dcf7ffeaa82f0a3-__lock__
```

Note, when outputting in 'directory' format, node data would not be printed at all.
